### ISSUE TITLE
How to get the complete reconstruction results?

### ISSUE THREAD

**Issue by JIANG-CX** [edexheim/como#5]
Wonderful work.
After running the code, I can only find the pose in the results file. How can I obtain the complete reconstruction results, similar to what is shown in Fig. 2 (c)? Thank you.

**Comment by edexheim** [comment]
Hello,

We store a buffer of keyframe images, poses and depth maps up to a maximum buffer size here: https://github.com/edexheim/como/blob/da616363454591085c3f02715d7d9df04388a19f/como/gui/GuiWindow.py#L545.  We saved these tensors for that visualization.

Let me know if you have any more questions.

**Comment by JIANG-CX** [comment]
Thank you for your response. I also noticed that the reconstruction results heavily rely on the quality of the sparse anchor points. Some outliers can significantly reduce the accuracy of the dense map. Is there any way to eliminate the impact of these outliers?

**Comment by edexheim** [comment]
Hello,

The sparse anchor points are inferred from photometric error between frames.  If assumptions of that are invalid for many parts of the image, for example, due to specularity, transparent surfaces, large exposure changes, the sparse anchor points will be optimized to incorrect places.  In general, we wanted to see how robust the representation can be with such a simple data term, but replacing this with learned features that are robust to these effects could significantly improve the accuracy at the expense of increased computation.  The photometric error is also calculated based on projective data association, which is subject to local minima, but other correspondence methods such as feature matching could also help avoid this.

Let me know if you have any more questions.

Best,
Eric

**Comment by JIANG-CX** [comment]
Thanks for your reply. It's a great work.
